# OAUTH2_PROVIDER_APPLICATION_MODEL = 'oauth.Client'
# OAUTH2_PROVIDER_GRANT_MODEL = 'oauth.Grant'

OAUTH2_PROVIDER = {
    "ACCESS_TOKEN_EXPIRE_SECONDS": 3600,
    # 'ALLOWED_REDIRECT_URI_SCHEMES': ['http', 'https'],
    # 'OIDC_ENABLED': True,
    # 'PKCE_REQUIRED': True,
}
