# Generated by Django 5.2 on 2025-11-29 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('humidity', models.FloatField(default=0)),
                ('temperature', models.FloatField(default=0)),
                ('wind_speed', models.FloatField(default=0)),
                ('pressure', models.FloatField(default=0)),
                ('precipitation', models.FloatField(default=0)),
                ('pm2_5', models.FloatField(default=0)),
                ('pm10', models.FloatField(default=0)),
                ('fog', models.SmallIntegerField(default=0)),
                ('aqi', models.FloatField(default=0)),
                ('station_name', models.CharField(blank=True, max_length=255, null=True)),
                ('station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='station.station')),
            ],
        ),
    ]
