# Generated by Django 5.2 on 2025-11-30 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='code',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
