# Generated by Django 5.2 on 2025-11-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('map_type', models.SmallIntegerField(choices=[(0, 'REGIONAL'), (1, 'DISTRICT')], default=0)),
                ('data', models.JSONField(default=dict)),
            ],
        ),
    ]
