# Generated by Django 5.2 on 2025-11-28 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_alter_map_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='data',
            field=models.FileField(upload_to='maps/'),
        ),
    ]
