# Generated by Django 5.2 on 2025-06-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='path_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
